export class UsuarioModel {
    id?;
    Foto?;
    Nombre?;
    email?;
    Apellido?;
    password?;
    Instructor?;
    Colaborador?;
    FechaCreacion?;
    FechaNacimiento?;
    CicloFormativo?;
    PlantillaCiclo?;
    Direccion?;
    Telefono?;
    Dni?;
    Cp?;
    Rol?;
    Provincia?;
    Ciudad?;
    TipoEvaluaciones?;
    Empresa?;
}
